-- AlterTable
ALTER TABLE "public"."Restaurant" ADD COLUMN     "baseDeliveryFee" DOUBLE PRECISION NOT NULL DEFAULT 3.5,
ADD COLUMN     "distanceRate" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN     "isAcive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "openTimes" JSONB,
ADD COLUMN     "serviceFeeRate" DOUBLE PRECISION NOT NULL DEFAULT 0.1;
